<html>
<head>
<title>asap.js</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<style type="text/css">
.s0 { color: #6a8759;}
.s1 { color: #a9b7c6;}
.s2 { color: #cc7832;}
.s3 { color: #808080;}
</style>
</head>
<body bgcolor="#2b2b2b">
<table CELLSPACING=0 CELLPADDING=5 COLS=1 WIDTH="100%" BGCOLOR="#606060" >
<tr><td><center>
<font face="Arial, Helvetica" color="#000000">
asap.js</font>
</center></td></tr></table>
<pre><span class="s0">&quot;use strict&quot;</span><span class="s1">;</span>

<span class="s2">var </span><span class="s1">rawAsap = require(</span><span class="s0">&quot;./raw&quot;</span><span class="s1">);</span>
<span class="s2">var </span><span class="s1">freeTasks = [];</span>

<span class="s3">/** 
 * Calls a task as soon as possible after returning, in its own event, with 
 * priority over IO events. An exception thrown in a task can be handled by 
 * `process.on(&quot;uncaughtException&quot;) or `domain.on(&quot;error&quot;)`, but will otherwise 
 * crash the process. If the error is handled, all subsequent tasks will 
 * resume. 
 * 
 * @param {{call}} task A callable object, typically a function that takes no 
 * arguments. 
 */</span>
<span class="s1">module.exports = asap;</span>
<span class="s2">function </span><span class="s1">asap(task) {</span>
    <span class="s2">var </span><span class="s1">rawTask;</span>
    <span class="s2">if </span><span class="s1">(freeTasks.length) {</span>
        <span class="s1">rawTask = freeTasks.pop();</span>
    <span class="s1">} </span><span class="s2">else </span><span class="s1">{</span>
        <span class="s1">rawTask = </span><span class="s2">new </span><span class="s1">RawTask();</span>
    <span class="s1">}</span>
    <span class="s1">rawTask.task = task;</span>
    <span class="s1">rawTask.domain = process.domain;</span>
    <span class="s1">rawAsap(rawTask);</span>
<span class="s1">}</span>

<span class="s2">function </span><span class="s1">RawTask() {</span>
    <span class="s2">this</span><span class="s1">.task = </span><span class="s2">null</span><span class="s1">;</span>
    <span class="s2">this</span><span class="s1">.domain = </span><span class="s2">null</span><span class="s1">;</span>
<span class="s1">}</span>

<span class="s1">RawTask.prototype.call = </span><span class="s2">function </span><span class="s1">() {</span>
    <span class="s2">if </span><span class="s1">(</span><span class="s2">this</span><span class="s1">.domain) {</span>
        <span class="s2">this</span><span class="s1">.domain.enter();</span>
    <span class="s1">}</span>
    <span class="s2">var </span><span class="s1">threw = </span><span class="s2">true</span><span class="s1">;</span>
    <span class="s2">try </span><span class="s1">{</span>
        <span class="s2">this</span><span class="s1">.task.call();</span>
        <span class="s1">threw = </span><span class="s2">false</span><span class="s1">;</span>
        <span class="s3">// If the task throws an exception (presumably) Node.js restores the</span>
        <span class="s3">// domain stack for the next event.</span>
        <span class="s2">if </span><span class="s1">(</span><span class="s2">this</span><span class="s1">.domain) {</span>
            <span class="s2">this</span><span class="s1">.domain.exit();</span>
        <span class="s1">}</span>
    <span class="s1">} </span><span class="s2">finally </span><span class="s1">{</span>
        <span class="s3">// We use try/finally and a threw flag to avoid messing up stack traces</span>
        <span class="s3">// when we catch and release errors.</span>
        <span class="s2">if </span><span class="s1">(threw) {</span>
            <span class="s3">// In Node.js, uncaught exceptions are considered fatal errors.</span>
            <span class="s3">// Re-throw them to interrupt flushing!</span>
            <span class="s3">// Ensure that flushing continues if an uncaught exception is</span>
            <span class="s3">// suppressed listening process.on(&quot;uncaughtException&quot;) or</span>
            <span class="s3">// domain.on(&quot;error&quot;).</span>
            <span class="s1">rawAsap.requestFlush();</span>
        <span class="s1">}</span>
        <span class="s3">// If the task threw an error, we do not want to exit the domain here.</span>
        <span class="s3">// Exiting the domain would prevent the domain from catching the error.</span>
        <span class="s2">this</span><span class="s1">.task = </span><span class="s2">null</span><span class="s1">;</span>
        <span class="s2">this</span><span class="s1">.domain = </span><span class="s2">null</span><span class="s1">;</span>
        <span class="s1">freeTasks.push(</span><span class="s2">this</span><span class="s1">);</span>
    <span class="s1">}</span>
<span class="s1">};</span>

</pre>
</body>
</html>