<html>
<head>
<title>ExceptionsManager.js</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<style type="text/css">
.s0 { color: #808080;}
.s1 { color: #a9b7c6;}
.s2 { color: #6a8759;}
.s3 { color: #cc7832;}
.s4 { color: #6897bb;}
</style>
</head>
<body bgcolor="#2b2b2b">
<table CELLSPACING=0 CELLPADDING=5 COLS=1 WIDTH="100%" BGCOLOR="#606060" >
<tr><td><center>
<font face="Arial, Helvetica" color="#000000">
ExceptionsManager.js</font>
</center></td></tr></table>
<pre><span class="s0">/** 
 * Copyright (c) Meta Platforms, Inc. and affiliates. 
 * 
 * This source code is licensed under the MIT license found in the 
 * LICENSE file in the root directory of this source tree. 
 * 
 * @format 
 * @flow strict 
 */</span>

<span class="s2">'use strict'</span><span class="s1">;</span>

<span class="s1">import type {ExtendedError} from </span><span class="s2">'./ExtendedError'</span><span class="s1">;</span>
<span class="s1">import type {ExceptionData} from </span><span class="s2">'./NativeExceptionsManager'</span><span class="s1">;</span>

<span class="s1">class SyntheticError extends Error {</span>
  <span class="s1">name: string = </span><span class="s2">''</span><span class="s1">;</span>
<span class="s1">}</span>

<span class="s1">type ExceptionDecorator = ExceptionData =&gt; ExceptionData;</span>

<span class="s1">let userExceptionDecorator: ?ExceptionDecorator;</span>
<span class="s1">let inUserExceptionDecorator = </span><span class="s3">false</span><span class="s1">;</span>

<span class="s0">// This Symbol is used to decorate an ExtendedError with extra data in select usecases.</span>
<span class="s0">// Note that data passed using this method should be strictly contained,</span>
<span class="s0">// as data that's not serializable/too large may cause issues with passing the error to the native code.</span>
<span class="s1">const decoratedExtraDataKey: symbol = Symbol(</span><span class="s2">'decoratedExtraDataKey'</span><span class="s1">);</span>

<span class="s0">/** 
 * Allows the app to add information to the exception report before it is sent 
 * to native. This API is not final. 
 */</span>

<span class="s3">function </span><span class="s1">unstable_setExceptionDecorator(</span>
  <span class="s1">exceptionDecorator: ?ExceptionDecorator,</span>
<span class="s1">) {</span>
  <span class="s1">userExceptionDecorator = exceptionDecorator;</span>
<span class="s1">}</span>

<span class="s3">function </span><span class="s1">preprocessException(data: ExceptionData): ExceptionData {</span>
  <span class="s3">if </span><span class="s1">(userExceptionDecorator &amp;&amp; !inUserExceptionDecorator) {</span>
    <span class="s1">inUserExceptionDecorator = </span><span class="s3">true</span><span class="s1">;</span>
    <span class="s3">try </span><span class="s1">{</span>
      <span class="s3">return </span><span class="s1">userExceptionDecorator(data);</span>
    <span class="s1">} </span><span class="s3">catch </span><span class="s1">{</span>
      <span class="s0">// Fall through</span>
    <span class="s1">} </span><span class="s3">finally </span><span class="s1">{</span>
      <span class="s1">inUserExceptionDecorator = </span><span class="s3">false</span><span class="s1">;</span>
    <span class="s1">}</span>
  <span class="s1">}</span>
  <span class="s3">return </span><span class="s1">data;</span>
<span class="s1">}</span>

<span class="s0">/** 
 * Handles the developer-visible aspect of errors and exceptions 
 */</span>
<span class="s1">let exceptionID = </span><span class="s4">0</span><span class="s1">;</span>
<span class="s3">function </span><span class="s1">reportException(</span>
  <span class="s1">e: ExtendedError,</span>
  <span class="s1">isFatal: boolean,</span>
  <span class="s1">reportToConsole: boolean, </span><span class="s0">// only true when coming from handleException; the error has not yet been logged</span>
<span class="s1">) {</span>
  <span class="s1">const parseErrorStack = require(</span><span class="s2">'./Devtools/parseErrorStack'</span><span class="s1">);</span>
  <span class="s1">const stack = parseErrorStack(e?.stack);</span>
  <span class="s1">const currentExceptionID = ++exceptionID;</span>
  <span class="s1">const originalMessage = e.message || </span><span class="s2">''</span><span class="s1">;</span>
  <span class="s1">let message = originalMessage;</span>
  <span class="s3">if </span><span class="s1">(e.componentStack != </span><span class="s3">null</span><span class="s1">) {</span>
    <span class="s1">message += `\n\nThis error is located at:${e.componentStack}`;</span>
  <span class="s1">}</span>
  <span class="s1">const namePrefix = e.name == </span><span class="s3">null </span><span class="s1">|| e.name === </span><span class="s2">'' </span><span class="s1">? </span><span class="s2">'' </span><span class="s1">: `${e.name}: `;</span>

  <span class="s3">if </span><span class="s1">(!message.startsWith(namePrefix)) {</span>
    <span class="s1">message = namePrefix + message;</span>
  <span class="s1">}</span>

  <span class="s1">message =</span>
    <span class="s1">e.jsEngine == </span><span class="s3">null </span><span class="s1">? message : `${message}, js engine: ${e.jsEngine}`;</span>

  <span class="s1">const data = preprocessException({</span>
    <span class="s1">message,</span>
    <span class="s1">originalMessage: message === originalMessage ? </span><span class="s3">null </span><span class="s1">: originalMessage,</span>
    <span class="s1">name: e.name == </span><span class="s3">null </span><span class="s1">|| e.name === </span><span class="s2">'' </span><span class="s1">? </span><span class="s3">null </span><span class="s1">: e.name,</span>
    <span class="s1">componentStack:</span>
      <span class="s3">typeof </span><span class="s1">e.componentStack === </span><span class="s2">'string' </span><span class="s1">? e.componentStack : </span><span class="s3">null</span><span class="s1">,</span>
    <span class="s1">stack,</span>
    <span class="s1">id: currentExceptionID,</span>
    <span class="s1">isFatal,</span>
    <span class="s1">extraData: {</span>
      <span class="s0">// $FlowFixMe[incompatible-use] we can't define a type with a Symbol-keyed field in flow</span>
      <span class="s1">...e[decoratedExtraDataKey],</span>
      <span class="s1">jsEngine: e.jsEngine,</span>
      <span class="s1">rawStack: e.stack,</span>
    <span class="s1">},</span>
  <span class="s1">});</span>

  <span class="s3">if </span><span class="s1">(reportToConsole) {</span>
    <span class="s0">// we feed back into console.error, to make sure any methods that are</span>
    <span class="s0">// monkey patched on top of console.error are called when coming from</span>
    <span class="s0">// handleException</span>
    <span class="s1">console.error(data.message);</span>
  <span class="s1">}</span>

  <span class="s3">if </span><span class="s1">(__DEV__) {</span>
    <span class="s1">const LogBox = require(</span><span class="s2">'../LogBox/LogBox'</span><span class="s1">).</span><span class="s3">default</span><span class="s1">;</span>
    <span class="s1">LogBox.addException({</span>
      <span class="s1">...data,</span>
      <span class="s1">isComponentError: !!e.isComponentError,</span>
    <span class="s1">});</span>
  <span class="s1">} </span><span class="s3">else if </span><span class="s1">(isFatal || e.type !== </span><span class="s2">'warn'</span><span class="s1">) {</span>
    <span class="s1">const NativeExceptionsManager =</span>
      <span class="s1">require(</span><span class="s2">'./NativeExceptionsManager'</span><span class="s1">).</span><span class="s3">default</span><span class="s1">;</span>
    <span class="s3">if </span><span class="s1">(NativeExceptionsManager) {</span>
      <span class="s1">NativeExceptionsManager.reportException(data);</span>
    <span class="s1">}</span>
  <span class="s1">}</span>
<span class="s1">}</span>

<span class="s1">declare </span><span class="s3">var </span><span class="s1">console: </span><span class="s3">typeof </span><span class="s1">console &amp; {</span>
  <span class="s1">_errorOriginal: </span><span class="s3">typeof </span><span class="s1">console.error,</span>
  <span class="s1">reportErrorsAsExceptions: boolean,</span>
  <span class="s1">...</span>
<span class="s1">};</span>

<span class="s0">// If we trigger console.error _from_ handleException,</span>
<span class="s0">// we do want to make sure that console.error doesn't trigger error reporting again</span>
<span class="s1">let inExceptionHandler = </span><span class="s3">false</span><span class="s1">;</span>

<span class="s0">/** 
 * Logs exceptions to the (native) console and displays them 
 */</span>
<span class="s3">function </span><span class="s1">handleException(e: mixed, isFatal: boolean) {</span>
  <span class="s1">let error: Error;</span>
  <span class="s3">if </span><span class="s1">(e </span><span class="s3">instanceof </span><span class="s1">Error) {</span>
    <span class="s1">error = e;</span>
  <span class="s1">} </span><span class="s3">else </span><span class="s1">{</span>
    <span class="s0">// Workaround for reporting errors caused by `throw 'some string'`</span>
    <span class="s0">// Unfortunately there is no way to figure out the stacktrace in this</span>
    <span class="s0">// case, so if you ended up here trying to trace an error, look for</span>
    <span class="s0">// `throw '&lt;error message&gt;'` somewhere in your codebase.</span>
    <span class="s1">error = </span><span class="s3">new </span><span class="s1">SyntheticError(e);</span>
  <span class="s1">}</span>
  <span class="s3">try </span><span class="s1">{</span>
    <span class="s1">inExceptionHandler = </span><span class="s3">true</span><span class="s1">;</span>
    <span class="s0">/* $FlowFixMe[class-object-subtyping] added when improving typing for this 
     * parameters */</span>
    <span class="s1">reportException(error, isFatal, </span><span class="s0">/*reportToConsole*/ </span><span class="s3">true</span><span class="s1">);</span>
  <span class="s1">} </span><span class="s3">finally </span><span class="s1">{</span>
    <span class="s1">inExceptionHandler = </span><span class="s3">false</span><span class="s1">;</span>
  <span class="s1">}</span>
<span class="s1">}</span>

<span class="s0">/* $FlowFixMe[missing-local-annot] The type annotation(s) required by Flow's 
 * LTI update could not be added via codemod */</span>
<span class="s3">function </span><span class="s1">reactConsoleErrorHandler(...args) {</span>
  <span class="s0">// bubble up to any original handlers</span>
  <span class="s1">console._errorOriginal(...args);</span>
  <span class="s3">if </span><span class="s1">(!console.reportErrorsAsExceptions) {</span>
    <span class="s3">return</span><span class="s1">;</span>
  <span class="s1">}</span>
  <span class="s3">if </span><span class="s1">(inExceptionHandler) {</span>
    <span class="s0">// The fundamental trick here is that are multiple entry point to logging errors:</span>
    <span class="s0">// (see D19743075 for more background)</span>
    <span class="s0">//</span>
    <span class="s0">// 1. An uncaught exception being caught by the global handler</span>
    <span class="s0">// 2. An error being logged throw console.error</span>
    <span class="s0">//</span>
    <span class="s0">// However, console.error is monkey patched multiple times: by this module, and by the</span>
    <span class="s0">// DevTools setup that sends messages to Metro.</span>
    <span class="s0">// The patching order cannot be relied upon.</span>
    <span class="s0">//</span>
    <span class="s0">// So, some scenarios that are handled by this flag:</span>
    <span class="s0">//</span>
    <span class="s0">// Logging an error:</span>
    <span class="s0">// 1. console.error called from user code</span>
    <span class="s0">// 2. (possibly) arrives _first_ at DevTool handler, send to Metro</span>
    <span class="s0">// 3. Bubbles to here</span>
    <span class="s0">// 4. goes into report Exception.</span>
    <span class="s0">// 5. should not trigger console.error again, to avoid looping / logging twice</span>
    <span class="s0">// 6. should still bubble up to original console</span>
    <span class="s0">//    (which might either be console.log, or the DevTools handler in case it patched _earlier_ and (2) didn't happen)</span>
    <span class="s0">//</span>
    <span class="s0">// Throwing an uncaught exception:</span>
    <span class="s0">// 1. exception thrown</span>
    <span class="s0">// 2. picked up by handleException</span>
    <span class="s0">// 3. should be sent to console.error (not console._errorOriginal, as DevTools might have patched _later_ and it needs to send it to Metro)</span>
    <span class="s0">// 4. that _might_ bubble again to the `reactConsoleErrorHandle` defined here</span>
    <span class="s0">//    -&gt; should not handle exception _again_, to avoid looping / showing twice (this code branch)</span>
    <span class="s0">// 5. should still bubble up to original console (which might either be console.log, or the DevTools handler in case that one patched _earlier_)</span>
    <span class="s3">return</span><span class="s1">;</span>
  <span class="s1">}</span>

  <span class="s1">let error;</span>

  <span class="s1">const firstArg = args[</span><span class="s4">0</span><span class="s1">];</span>
  <span class="s3">if </span><span class="s1">(firstArg?.stack) {</span>
    <span class="s0">// reportException will console.error this with high enough fidelity.</span>
    <span class="s1">error = firstArg;</span>
  <span class="s1">} </span><span class="s3">else </span><span class="s1">{</span>
    <span class="s1">const stringifySafe = require(</span><span class="s2">'../Utilities/stringifySafe'</span><span class="s1">).</span><span class="s3">default</span><span class="s1">;</span>
    <span class="s3">if </span><span class="s1">(</span><span class="s3">typeof </span><span class="s1">firstArg === </span><span class="s2">'string' </span><span class="s1">&amp;&amp; firstArg.startsWith(</span><span class="s2">'Warning: '</span><span class="s1">)) {</span>
      <span class="s0">// React warnings use console.error so that a stack trace is shown, but</span>
      <span class="s0">// we don't (currently) want these to show a redbox</span>
      <span class="s0">// (Note: Logic duplicated in polyfills/console.js.)</span>
      <span class="s3">return</span><span class="s1">;</span>
    <span class="s1">}</span>
    <span class="s1">const message = args</span>
      <span class="s1">.map(arg =&gt; (</span><span class="s3">typeof </span><span class="s1">arg === </span><span class="s2">'string' </span><span class="s1">? arg : stringifySafe(arg)))</span>
      <span class="s1">.join(</span><span class="s2">' '</span><span class="s1">);</span>

    <span class="s1">error = </span><span class="s3">new </span><span class="s1">SyntheticError(message);</span>
    <span class="s1">error.name = </span><span class="s2">'console.error'</span><span class="s1">;</span>
  <span class="s1">}</span>

  <span class="s1">reportException(</span>
    <span class="s0">/* $FlowFixMe[class-object-subtyping] added when improving typing for this 
     * parameters */</span>
    <span class="s1">error,</span>
    <span class="s3">false</span><span class="s1">, </span><span class="s0">// isFatal</span>
    <span class="s3">false</span><span class="s1">, </span><span class="s0">// reportToConsole</span>
  <span class="s1">);</span>
<span class="s1">}</span>

<span class="s0">/** 
 * Shows a redbox with stacktrace for all console.error messages.  Disable by 
 * setting `console.reportErrorsAsExceptions = false;` in your app. 
 */</span>
<span class="s3">function </span><span class="s1">installConsoleErrorReporter() {</span>
  <span class="s0">// Enable reportErrorsAsExceptions</span>
  <span class="s3">if </span><span class="s1">(console._errorOriginal) {</span>
    <span class="s3">return</span><span class="s1">; </span><span class="s0">// already installed</span>
  <span class="s1">}</span>
  <span class="s0">// Flow doesn't like it when you set arbitrary values on a global object</span>
  <span class="s1">console._errorOriginal = console.error.bind(console);</span>
  <span class="s1">console.error = reactConsoleErrorHandler;</span>
  <span class="s3">if </span><span class="s1">(console.reportErrorsAsExceptions === undefined) {</span>
    <span class="s0">// Individual apps can disable this</span>
    <span class="s0">// Flow doesn't like it when you set arbitrary values on a global object</span>
    <span class="s1">console.reportErrorsAsExceptions = </span><span class="s3">true</span><span class="s1">;</span>
  <span class="s1">}</span>
<span class="s1">}</span>

<span class="s1">module.exports = {</span>
  <span class="s1">decoratedExtraDataKey,</span>
  <span class="s1">handleException,</span>
  <span class="s1">installConsoleErrorReporter,</span>
  <span class="s1">SyntheticError,</span>
  <span class="s1">unstable_setExceptionDecorator,</span>
<span class="s1">};</span>
</pre>
</body>
</html>